### ISSUE TITLE
crash on archlinux: cannot allocate memory in static TLS block

### ISSUE THREAD

**Issue by cyberic99** [pythonspeed/filprofiler#133]
Hello.
I get this error on 2 of my computers, both running archlinux.

One is running Python 3.8.6, the other Python 3.9.1.
```
fil-profile run /tmp/p.py 
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/od/.local/lib/python3.8/site-packages/filprofiler/_script.py", line 217, in <module>
    stage_2()
  File "/home/od/.local/lib/python3.8/site-packages/filprofiler/_script.py", line 202, in stage_2
    from ._tracer import trace_until_exit, create_report
  File "/home/od/.local/lib/python3.8/site-packages/filprofiler/_tracer.py", line 24, in <module>
    preload = PyDLL(library_path("_filpreload"))
  File "/usr/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/od/.local/lib/python3.8/site-packages/filprofiler/_filpreload.cpython-38-x86_64-linux-gnu.so: cannot allocate memory in static TLS block
```

```
fil-profile --version
```
```
0.15.0
```
Is there anything I could do to investigate?

Thanks

**Comment by itamarst** [comment]
Thanks for the bug report! I'm not superfamiliar with Arch, are you using a specific version of Arch?

Can you try changing line 24 of /home/od/.local/lib/python3.8/site-packages/filprofiler/_tracer.py to `preload = PyDLL(None)` and see if it helps?

**Comment by cyberic99** [comment]
> are you using a specific version of Arch?

Arch is a rolling release, so there is no fixed version.

Now I get this:
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/od/.local/lib/python3.8/site-packages/filprofiler/_script.py", line 217, in <module>
    stage_2()
  File "/home/od/.local/lib/python3.8/site-packages/filprofiler/_script.py", line 202, in stage_2
    from ._tracer import trace_until_exit, create_report
  File "/home/od/.local/lib/python3.8/site-packages/filprofiler/_tracer.py", line 26, in <module>
    preload.fil_initialize_from_python()
  File "/usr/lib/python3.8/ctypes/__init__.py", line 386, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python3.8/ctypes/__init__.py", line 391, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/bin/python3: undefined symbol: fil_initialize_from_python
```

**Comment by itamarst** [comment]
Huh. That seems like... the shared library isn't being LD_PRELOADed? Which would explain both symptoms, but seems unexpected.

I'll try to spin up a Docker image tomorrow with Arch and see if I can figure it out.

**Comment by itamarst** [comment]
Theory #2: Packages shipped without the shared library. Does not appear to be the case, it works when I install from scratch.

Theory #3: Some existing LD_PRELOAD stuff is messing with Fil.

Can you share the output of the following two commands?

```
$ env | grep LD_PRELOAD
$ cat /etc/ld.so.preload
```

**Comment by itamarst** [comment]
I spun up a new `archlinux` Docker image, did `pacman -Sy python3 python-pip`, pip installed filprofiler, and then ran it on pystone.py. It worked.

This suggests it's some environmental issue, perhaps the LD_PRELOAD (theory 3) mentioned above, so that information will be helpful in debugging.

**Comment by itamarst** [comment]
Theory 4: `--user` installs are a problem. Tested, seems fine.

@cyberic99, if you have the time, could you share the output of:

```console
$ env | grep LD_PRELOAD
$ cat /etc/ld.so.preload
$ env LD_PRELOAD=$(ls ~/.local/lib/python3.9/site-packages/filprofiler/_filpreload*.so) python -m filprofiler._script run example.py  # may need to switch to 3.8
$ /lib/ld-linux-x86-64.so.2 --preload $(ls ~/.local/lib/python3.9/site-packages/filprofiler/_filpreload*.so) /usr/bin/python3.9 -m filprofiler._script run example.py   # may need to switch to python 3.8
```

If you're feeling very generous with your time, I'd be happy to do a screen sharing session to debug this.

Thank you!

**Comment by cyberic99** [comment]
> $ env | grep LD_PRELOAD

no output

> $ cat /etc/ld.so.preload

cat: /etc/ld.so.preload: No such file or directory

> Theory 4: --user installs are a problem. Tested, seems fine.

I tested system-wise install on my side, and have the same issue

> env LD_PRELOAD=$(ls ~/.local/lib/python3.9/site-packages/filprofiler/_filpreload*.so) python -m filprofiler._script run /tmp/p.py

```
env LD_PRELOAD=$(ls ~/.local/lib/python3.9/site-packages/filprofiler/_filpreload*.so) python -m filprofiler._script run /tmp/p.py 
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/eric/.local/lib/python3.9/site-packages/filprofiler/_script.py", line 217, in <module>
    stage_2()
  File "/home/eric/.local/lib/python3.9/site-packages/filprofiler/_script.py", line 202, in stage_2
    from ._tracer import trace_until_exit, create_report
  File "/home/eric/.local/lib/python3.9/site-packages/filprofiler/_tracer.py", line 24, in <module>
    preload = PyDLL(library_path("_filpreload"))
  File "/usr/lib/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/eric/.local/lib/python3.9/site-packages/filprofiler/_filpreload.cpython-39-x86_64-linux-gnu.so: cannot allocate memory in static TLS block
```

I also found something strange:
```
env LD_PRELOAD=$(ls ~/.local/lib/python3.9/site-packages/filprofiler/_filpreload*.so) ls
```
```
ls: symbol lookup error: /home/eric/.local/lib/python3.9/site-packages/filprofiler/_filpreload.cpython-39-x86_64-linux-gnu.so: undefined symbol: trunc
```

I'll try to fully upgrade my current installation and try this on another computer too. I keep you posted. 

And thanks for your time!

**Comment by itamarst** [comment]
That last error is expected, I'm preloading the shared library into what should be the Python executable, which will be linked to `libm` which has `trunc`, and `ls` isn't linked to that.

This is very mysterious...

Did the ` /lib/ld-linux-x86-64.so.2` variant give the same error?

**Comment by cyberic99** [comment]
ha sorry, I hadn' tried the last variant, and it works!
you did it ! ;-)

If you have other things to try/consolidate, please tell me

**Comment by itamarst** [comment]
I was thinking of using that when possible (requires fairly new Linux I think?) for other reasons, but... would be nice to know why that worked and other options didn't. I will go read some man pages and see if anything leaps out at me for you to try. Many thanks for debugging help so far!

**Comment by cyberic99** [comment]
> Many thanks for debugging help so far!

no problem, thanks for taking the time to solve this issue!

**Comment by cyberic99** [comment]
I would like to try to use the API and not profile my entiere program. is it possible using this ld-linux way?

**Comment by itamarst** [comment]
It is possible, yeah. I will try to do a new release today that uses this method when possible (it requires glibc from 2019), so you can just use the 0.16 release when it comes out.

**Comment by itamarst** [comment]
What kind of software are you profiling BTW, and why does reducing memory usage matter to you?

**Comment by cyberic99** [comment]
It is a software we designed with my pal from The Other Days, a french chiptune band.
We drive 8-bit and 16-bit era sound chips of different types, in real time, wired with arduinos or teensys, in order to play songs directly on the real hardware.
And we orchestrate all this using python.
Recently we started to do some serious CPU and memory benchmarking to know what kind of hardware we would need to get a good performance. I tried a lot of CPU and memory profilers for python, and I stumbled upon filprofiler.
Currently, our software needs up to 2GB memory for some songs, so I'd be interested in reducing this a bit.
Also, a lot of time is spent on queue.get(), because we share some messages from processes to others.
So I'd like to skip this part when benchmarking the CPU usage.
Does it sanswer to your question? ;-)

**Comment by cyberic99** [comment]
(also, I can install a snapshot from the current master with pip if you need me to do some tests before the release)

**Comment by itamarst** [comment]
Huh, that's cool, didn't expect that use case when I wrote it.

When the PR to work around this issue is done, I'll share a wheel you can try out.

**Comment by cyberic99** [comment]
> didn't expect that use case when I wrote it.

right. but in fact, profiling a program or trying to optimize it can be done for any software, right? ;-)

**Comment by itamarst** [comment]
Oh, definitely, and if Fil does end up helping you I'd love to do an interview for a case study. Just... not what what I expected :) My main goal is to help scientists.

**Comment by itamarst** [comment]
Can you test the wheels in the attached ZIP? Basically `pip install --upgrade path/to/unzipped/.whl`.
[ubuntu-20.04-3.8-wheel.zip](https://github.com/pythonspeed/filprofiler/files/6032007/ubuntu-20.04-3.8-wheel.zip)

**Comment by itamarst** [comment]
Just going to merge, worst case can do another iteration on fixing this.

**Comment by cyberic99** [comment]
sorry, I had no time to test your changes, I'll do it soon and report here

**Comment by cyberic99** [comment]
So the ``run`` methods runs fine.

the ``python`` method gives this:

```
Failed to preload the Fil shared library: /usr/bin/python3: undefined symbol: fil_initialize_from_python.

This can happen on Linux for unknown reasons on versions of glibc older than 2.30. Upgrading to a version of Linux from 2020 or later might solve this.

If you're on macOS or a sufficiently new Linux, you've found a bug! You can file an issue or just ask for help at:
https://github.com/pythonspeed/filprofiler/issues/new/choose

Full trackback:

Traceback (most recent call last):
  File "/home/eric/.local/lib/python3.9/site-packages/filprofiler/_tracer.py", line 25, in <module>
    preload.fil_initialize_from_python()
  File "/usr/lib/python3.9/ctypes/__init__.py", line 387, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python3.9/ctypes/__init__.py", line 392, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/bin/python3: undefined symbol: fil_initialize_from_python
```

but only when I launch my program, which is quite complex and involves threads, processes etc

a simple trivial program works correctly.

Also, my glibc is 2.33-4

**Comment by itamarst** [comment]
Thanks for trying it! Guess I need to write some more tests. Subprocesses aren't supported but that doesn't look like what the issue is.

**Comment by itamarst** [comment]
How do you launch subprocesses in your code?

**Comment by itamarst** [comment]
Possibly this isn't so much a bug as a UX issue, if a subprocess tries to use the Fil APIs it should explicitly disallow it for now, the same way Jupyter does.

**Comment by cyberic99** [comment]
> How do you launch subprocesses in your code?

I have a MyProcess() class, which calls ctx.Process() to create ``Process`` objects.
with ctx being a ``multiprocessing.get_context('forkserver')``

**Comment by itamarst** [comment]
Can you try the attached wheels with whatever you were doing with `fil-profile python`? My expectation is that it still won't work, but you will get a nice meaningful error message this time.

[ubuntu-20.04-3.8-wheel(1).zip](https://github.com/pythonspeed/filprofiler/files/6062509/ubuntu-20.04-3.8-wheel.1.zip)

**Comment by cyberic99** [comment]
Sorry @itamarst but I can't install it:
```shell
$ python3 -mpip install   /home/eric/Downloads/ubuntu-20.04-3.8-wheel.1.zip  --user
```
```python
Processing ./ubuntu-20.04-3.8-wheel.1.zip
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-al8xjfl0/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-al8xjfl0/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-80_6n0fx
         cwd: /tmp/pip-req-build-al8xjfl0/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3.9/tokenize.py", line 392, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-req-build-al8xjfl0/setup.py'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by cyberic99** [comment]
no, my bad, of course I have to unzip it ;-)

you were right, the results are pretty clear ;-)

```python
ERROR: RuntimeError in MidiPlaybackSession(Toki_sndh_SHA256.mid) pid=82964 dmn_pid=82925: Fil does not yet support tracing in subprocesses, so starting the parent process with Fil is not sufficient for Fil APIs to work in child processes. @Process.py:465
Traceback (most recent call last):
  File "/data/od/od/midi-tools/midi-player/Process.py", line 465, in my_run_process
    self.run()
  File "/data/od/od/midi-tools/midi-player/MidiPlaybackSession.py", line 1230, in run
    result = profile(lambda: self.run2(), "/tmp/fil-result")
  File "/home/eric/.local/lib/python3.9/site-packages/filprofiler/api.py", line 28, in profile
    from ._tracer import (
  File "/home/eric/.local/lib/python3.9/site-packages/filprofiler/_tracer.py", line 36, in <module>
    check_if_fil_preloaded()
  File "/home/eric/.local/lib/python3.9/site-packages/filprofiler/_tracer.py", line 29, in check_if_fil_preloaded
    raise RuntimeError(
RuntimeError: Fil does not yet support tracing in subprocesses, so starting the parent process with Fil is not sufficient for Fil APIs to work in child processes.
```

I started my program with:
```shell
fil-profile python myprogram.py
```

**Comment by itamarst** [comment]
Thank you! Eventually I hope to support subprocesses (#80) , but for now, yeah, won't work.

OK, I'll merge this and mark the issue as closed.
