### ISSUE TITLE
Error writing SVG: I/O error: No stack counts found

### ISSUE THREAD

**Issue by npalombo** [pythonspeed/filprofiler#135]
## Version information
Fil: 0.15.0
Python: 3.8.6 (default, Oct 26 2020, 20:21:46) 
[Clang 11.0.3 (clang-1103.0.32.62)]

Running on MacOS 11.2.1. Using example.py from https://github.com/pythonspeed/filprofiler/blob/master/tests/test-scripts/example.py. Empty peak-memory.prof file created.

(.venv) ~/Projects/data-sources $ fil-profile run example.py 
=fil-profile= Memory usage will be written out at exit, and opened automatically in a browser.
=fil-profile= You can also run the following command while the program is still running to write out peak memory usage up to that point: kill -s SIGUSR2 71645
DEMO TIME!
DONE! 2.552993059158325
=fil-profile= Preparing to write to fil-result/2021-02-18T22:12:29.759
=fil-profile= Error writing SVG: I/O error: No stack counts found
=fil-profile= Error writing SVG: I/O error: No stack counts found
=fil-profile= Wrote HTML report to fil-result/2021-02-18T22:12:29.759/index.html
0:109: execution error: File some object wasn’t found. (-43)

**Comment by itamarst** [comment]
Thank you for the bug report, I will look in to it today.

**Comment by itamarst** [comment]
Was able to reproduce locally.

So there's two problems:

1. The reported bug.
2. Why didn't the test suite catch this?

**Comment by itamarst** [comment]
As a temporary measure I have deleted Fil 0.15 (macOS) from PyPI, so people get 0.14.1 instead.
