### ISSUE TITLE
Panic due to unwrap

### ISSUE THREAD

**Issue by rachtsingh** [pythonspeed/filprofiler#147]
I'm not entirely sure this is due to filprofile, but I can't get it to work on my program because of the following error:

```
=fil-profile= Memory usage will be written out at exit, and opened automatically in a browser.
=fil-profile= You can also run the following command while the program is still running to write out peak memory usage up to that point: kill -s SIGUSR2 75508
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/cgroups-rs-0.2.3/src/memory.rs:115:37
stack backtrace:
   0: rust_begin_unwind
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/panicking.rs:92:14
   2: core::panicking::panic
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/panicking.rs:50:5
   3: cgroups_rs::memory::MemController::memory_stat
   4: filpreload::add_allocation
   5: add_allocation
             at /src/filprofiler/_filpreload.c:306:3
   6: malloc
             at /src/filprofiler/_filpreload.c:344:5
   7: _PyObject_GC_Malloc
   8: _PyObject_GC_NewVar
   9: _PyFrame_New_NoTrack
  10: _PyFunction_FastCallKeywords
  11: <unknown>
  12: _PyEval_EvalFrameDefault
  13: _PyFunction_FastCallKeywords
  14: <unknown>
  15: _PyEval_EvalFrameDefault
  16: _PyEval_EvalCodeWithName
  17: _PyFunction_FastCallKeywords
  18: <unknown>
  19: _PyEval_EvalFrameDefault
  20: _PyEval_EvalCodeWithName
  21: _PyFunction_FastCallKeywords
  22: <unknown>
  23: _PyEval_EvalFrameDefault
  24: _PyEval_EvalCodeWithName
  25: PyEval_EvalCodeEx
  26: PyEval_EvalCode
  27: <unknown>
  28: _PyMethodDef_RawFastCallKeywords
  29: _PyCFunction_FastCallKeywords
  30: <unknown>
  31: _PyEval_EvalFrameDefault
  32: _PyEval_EvalCodeWithName
  33: _PyFunction_FastCallKeywords
  34: <unknown>
  35: _PyEval_EvalFrameDefault
  36: _PyEval_EvalCodeWithName
  37: _PyFunction_FastCallDict
  38: <unknown>
  39: <unknown>
  40: _Py_UnixMain
  41: __libc_start_main
  42: <unknown>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
fatal runtime error: failed to initiate panic, error 5
```

I'll try to provide a real reproducer if I can, but it's quite difficult, since we have an odd runtime environment.

**Comment by itamarst** [comment]
First, sorry this failed for you.

Second, this is probably a place in the codewhere errors shouldn't be fatal, so I will try to fix it to provide an error message, which should help with debugging. Sometime this week, maybe even tomorrow if I have time.

**Comment by itamarst** [comment]
That being said, could you give a bit more details about your runtime environment, just so I have a sense?

**Comment by rachtsingh** [comment]
Thanks for the response! Well, we have a regular Python installation in RHEL, except that our import mechanism has a few custom tweaks in it (i.e. we intercept imports, I think). I don't think that's the cause of this problem, though? Let me know if there's a better way to run this to give a more detailed stacktrace (`RUST_BACKTRACE=full` didn't seem to work).

**Comment by itamarst** [comment]
The import mechanism wouldn't be relevant, this is about the Linux environment.

1. Which version of RHEL?
2. Are you using containers in any way? (Docker, podman, singularity, something else)

**Comment by itamarst** [comment]
If you unzip this, you will find some wheels. If you install the one for the version of Python you use, you should be able to test it. The expectation is that the error will be printed, but Fil will continue to work: [ubuntu-20.04-3.8-wheel(2).zip](https://github.com/pythonspeed/filprofiler/files/6230940/ubuntu-20.04-3.8-wheel.2.zip)

**Comment by itamarst** [comment]
Just checking again, @rachtsingh might you have a chance to try this out?

**Comment by wikihoops** [comment]
Having had the same issue, I did try this out. Worked as you expected.

**Comment by itamarst** [comment]
> Having had the same issue, I did try this out. Worked as you expected.

So worth merging, then, thank you! What environment are you running in?

**Comment by wikihoops** [comment]
> What environment are you running in?

CentOS 7

[I haven’t actually managed to get any output in `fil-result/` but I assume this is unrelated to this issue.]

**Comment by rachtsingh** [comment]
Hey Itamar,

I'm sorry, just got a chance to try this today. Thank you for the support! I am on RHEL 7.9.

I tried your wheel, and it seems to mostly work! At least, I am getting useful output from it in the form I expect. Here's a few weird errors that I see in the output:

```
=fil-profile= Error retrieving cgroup memory, per-container/per-cgroup memory limits won't be respected (error: Any). Please file a bug at https://github.com/pythonspeed/filprofiler/issues/new/choose.
=fil-profile= Memory usage will be written out at exit, and opened automatically in a browser.
=fil-profile= You can also run the following command while the program is still running to write out peak memory usage up to that point: kill -s SIGUSR2 111307
=fil-profile= WARNING: Fil does not (yet) support tracking memory in subprocesses.
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 232, in 'calling callback function'
  File "../lib/venv3/lib64/python3.7/site-packages/threadpoolctl.py", line 400, in match_module_callback
    self._make_module_from_path(filepath)
  File "../lib/venv3/lib64/python3.7/site-packages/threadpoolctl.py", line 515, in _make_module_from_path
    module = module_class(filepath, prefix, user_api, internal_api)
  File "../lib/venv3/lib64/python3.7/site-packages/threadpoolctl.py", line 606, in __init__
    self.version = self.get_version()
  File "../lib/venv3/lib64/python3.7/site-packages/threadpoolctl.py", line 711, in get_version
    self._dynlib.mkl_get_version_string(res, 200)
  File "/opt/python/python-3.7/lib64/python3.7/ctypes/__init__.py", line 372, in __getattr__
    func = self.__getitem__(name)
  File "/opt/python/python-3.7/lib64/python3.7/ctypes/__init__.py", line 377, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/local/lib/libmkl_rt.so: undefined symbol: mkl_get_version_string
```

Though, it seems to bypass this error and profile correctly. It looks like an MKL mismatch, which is not a huge deal.

Thank you for writing a useful tool!

**Comment by itamarst** [comment]
`threadpoolctl` is a library I depend on, and yeah that'd be a bug in their code (or just a decision not to support certain versions of mkl? You could file a bug with them I guess).

Glad it's working, and let me know if you have any other questions, ideas, or problems.
