### ISSUE TITLE
Conda-forge packaging

### ISSUE THREAD

**Issue by itamarst** [pythonspeed/filprofiler#20]
For those who use Conda.

**Comment by owenlamont** [comment]
I'd like this - I want to try filprofiler but am very much a conda only Python developer.

**Comment by itamarst** [comment]
In the short term you can actually install pip packages in Conda, e.g. https://stackoverflow.com/questions/41060382/using-pip-to-install-packages-to-anaconda-environment

**Comment by owenlamont** [comment]
I was aware of that - as I understand it though it is then very risky to further update packages in an environment once you mix pip and conda packages. You have to remake the environment from scratch each time you update (I could be wrong about that now - I know Anaconda tries to improve how well conda and pip packages play together).

**Comment by itamarst** [comment]
I've done it in the past, with no ill effects, for what it's worth. Just need to be careful to not install any pip packages when conda packages are available.

In any case, I will try to prioritize creating conda-forge packages.

**Comment by itamarst** [comment]
Started work on this here: https://github.com/conda-forge/staged-recipes/pull/12377

**Comment by itamarst** [comment]
Fil is now on conda-forge. Need to test it manually, and then update docs.

**Comment by owenlamont** [comment]
Thanks @itamarst! I really appreciate your effort.
