### ISSUE TITLE
disable OOM kill and/or include swap

### ISSUE THREAD

**Issue by artemisart** [pythonspeed/filprofiler#201]
Hello, awesome tool !
Would it be possible to disable killing on OOM or include swap space in the calculation before killing ? with something like --ignore-oom and --oom-include-swap maybe ? Thanks :)

**Comment by itamarst** [comment]
When you say "killing on OOM", what behavior are you seeing?

1. Fil has a mechanism to try to detect OOM and dump a report in advance, so you can see what happened.
2. Both Linux and macOS will kill -9 processes using too much memory.

What behavior would you like to see instead of observed behavior?

**Comment by artemisart** [comment]
Yes I'm talking about 1, fil try to detects OOM but ignore the swap space while doing so, which can be unwanted (at least I believe it should be configurable).

https://github.com/pythonspeed/filprofiler/blob/dd9ccb1f0330a1485294a4714033d46e0432a4ba/memapi/src/oom.rs#L58-L68
For this `let available_bytes` should be `self.memory_info.get_available_memory();` + swap free space.

**Comment by itamarst** [comment]
I can try, but... both Linux and macOS have their own heuristics so the OS might kill things and then you get nothing. So in general I expect to be biased towards killing early. On the other hand, if your program would complete when run without Fil, killing early is definitely a bug. What OS are you on? Do you expect your program to complete without running out of memory when not using Fil?

**Comment by itamarst** [comment]
Given the OOM detection is a heuristic, and might always be wrong, the thing to do is probably add a `--disable-oom-detection` flag, to just allow opt out when it guesses wrong.

**Comment by itamarst** [comment]
Release 2021.7.0 is now out with this change; it should be up on PyPI within a few minutes, and on Conda-Forge by tomorrow, hopefully.

**Comment by artemisart** [comment]
I understand for the heuristic (well personally every server/laptop I had crawled for hours before doing on oom kill).

> On the other hand, if your program would complete when run without Fil, killing early is definitely a bug. What OS are you on?

Yes it would have completed without fil, this is on a ubuntu 18.04 server. I can give you the fil logs if you need it, but basically I had 30GB ram, 98% used, and 60GB of swap nearly 100% free.
I believe you could use the heuristic (ram_available_bytes + swap_free) / (ram_total + swap_total) > 98%, maybe under a --oom-include-swap.

> Given the OOM detection is a heuristic, and might always be wrong, the thing to do is probably add a `--disable-oom-detection` flag, to just allow opt out when it guesses wrong.
> Release 2021.7.0 is now out with this change; it should be up on PyPI within a few minutes, and on Conda-Forge by tomorrow, hopefully.

Awesome ! Thanks :)

**Comment by itamarst** [comment]
I was forced to yank the latest release due to #208 (the wheels are broken on some OSes in a way that wasn't caught by CI) so if you do new installs you will get older version for now until I get more tests and a bugfix out. If that's a problem let me know and I will post the wheels here for manual download.

**Comment by itamarst** [comment]
Release 2021.7.1 should be up on PyPI shortly.
