### ISSUE TITLE
Profile image isn't expand to 100% of my screen width

### ISSUE THREAD

**Issue by mayli** [pythonspeed/filprofiler#227]
## Version information
Fil: 2021.8.0
Python: 3.7.8 (default, Jun 29 2020, 05:44:46) 
[GCC 7.5.0]

![image](https://user-images.githubusercontent.com/822628/132431264-a373d9be-231c-447a-b52b-aa4aa5a10fca.png)
![image](https://user-images.githubusercontent.com/822628/132431279-3bd0fa72-36d7-45f0-90dc-b4a8b4913427.png)

The fullscreen button isn't working either :/

the Console throws
![image](https://user-images.githubusercontent.com/822628/132431364-cd4c18f7-9bb6-4568-a499-d6457eef0452.png)

It's a fairly middle sized profile result at 35MB.

**Comment by itamarst** [comment]
That seems like a problem. What browser are you using?

**Comment by mayli** [comment]
> That seems like a problem. What browser are you using?

Chrome Version 92.0.4515.159 (Official Build) (64-bit)

**Comment by mayli** [comment]
Looks like the fullscreen button is working fine in firefox

**Comment by itamarst** [comment]
Oh, Chrome addon. OK. Please file additional issues if you have any other problems!
