### ISSUE TITLE
Symbol not found: _PyExc_BaseException when shelling out to homebrew git under fil-profile

### ISSUE THREAD

**Issue by dreid** [pythonspeed/filprofiler#230]
I'm attempting to instrument a program that shells out to git during it's normal course of work.  When attempting to shell out to Homebrew git version 2.33.0 on macOS Big Sur 11.5.2 and python 3.8.10 from the python.org installer subprocess exits with the following Symbol not found and a SIGABRT:

```
dyld: Symbol not found: _PyExc_BaseException
  Referenced from: /Users/dreid/filtest/venv/lib/python3.8/site-packages/filprofiler/_filpreload.cpython-38-darwin.so
  Expected in: flat namespace
 in /Users/dreid/filtest/venv/lib/python3.8/site-packages/filprofiler/_filpreload.cpython-38-darwin.so
```

This does *not* occur with the system git.

## Test script

```python3
from subprocess import check_output, CalledProcessError

def git_config_list(path):
    try:
        check_output([path, "config", "--list"])
        return "ok"
    except CalledProcessError as e:
        print(e)
        return "failed"

print(f"System git  : {git_config_list('/usr/bin/git')}")
print(f"Homebrew git: {git_config_list('/usr/local/bin/git')}")
```

## Test output
```
❯❯ fil-profile run t.py
=fil-profile= Memory usage will be written out at exit, and opened automatically in a browser.
=fil-profile= You can also run the following command while the program is still running to write out peak memory usage up to that point: kill -s SIGUSR2 98912
=fil-profile= WARNING: Fil does not (yet) support tracking memory in subprocesses.
System git  : ok
dyld: Symbol not found: _PyExc_BaseException
  Referenced from: /Users/dreid/filtest/venv/lib/python3.8/site-packages/filprofiler/_filpreload.cpython-38-darwin.so
  Expected in: flat namespace
 in /Users/dreid/filtest/venv/lib/python3.8/site-packages/filprofiler/_filpreload.cpython-38-darwin.so
Command '['/usr/local/bin/git', 'config', '--list']' died with <Signals.SIGABRT: 6>.
Homebrew git: failed
=fil-profile= Preparing to write to fil-result/2021-09-13T09:44:48.550
=fil-profile= Wrote memory usage flamegraph to fil-result/2021-09-13T09:44:48.550/peak-memory.svg
=fil-profile= Wrote memory usage flamegraph to fil-result/2021-09-13T09:44:48.550/peak-memory-reversed.svg
=fil-profile= Wrote HTML report to fil-result/2021-09-13T09:44:48.550/index.html
0:89: execution error: File some object wasn’t found. (-43)
```

## Versions

```
❯❯ sw_vers
ProductName:	macOS
ProductVersion:	11.5.2
BuildVersion:	20G95

❯❯ python --version
Python 3.8.10

❯❯ fil-profile --version
2021.8.0

❯❯ /usr/bin/git version --build-options
git version 2.30.1 (Apple Git-130)
cpu: x86_64
no commit associated with this build
sizeof-long: 8
sizeof-size_t: 8
shell-path: /bin/sh

❯❯ /usr/local/bin/git version --build-options
git version 2.33.0
cpu: x86_64
no commit associated with this build
sizeof-long: 8
sizeof-size_t: 8
shell-path: /bin/sh
```

I have additionally been able to reproduce this error with homebrew Python 3.8.12 and homebrew python 3.9.5.

**Comment by itamarst** [comment]
That sounds annoying. Thank you for the very detailed bug report. I'll see what I can figure out.

**Comment by itamarst** [comment]
Was able to reproduce.

**Comment by itamarst** [comment]
The problem is due to leaving `DYLD_INSERT_LIBRARIES` env variable (macOS equivalent of LD_PRELOAD) alone and not unsetting it as I do for `LD_PRELOAD`. This was done to fix #135. #137 suggests that CI won't catch the problem in #135.

I have since tweaked how Fil is built so maybe that'll make this easier.

**Comment by itamarst** [comment]
Apparently the problem is clearing `DYLD_INSERT_LIBRARIES` in the shared library constructor. If clearing is done later in the process lifetime, everything works, including the test case above. So that's the solution, next question is how to test this without requiring homebrew.

...

I guess CI at least already assumes Homebrew? So maybe that's fine.

**Comment by itamarst** [comment]
(Also there's still #137, but tests pass on my dev machine which was able to reproduce #135 previously, so #137 is not a blocker.)

**Comment by itamarst** [comment]
New release with this fix should be available on PyPI in the next 30 minutes or so.
