### ISSUE TITLE
Script to monitor freeze when sending SIGUSR2 signal

### ISSUE THREAD

**Issue by gaspard-quenard** [pythonspeed/filprofiler#237]
Hi, 
I cannot succeed to dump a fil memory profile when using the command `kill -USR2 <process-pid>`. The script seems to freeze when I try to send this signal.

Step to reproduce: 

Here is the script I tried to monitor:

```python
import time

class LeakClass():

    def __init__(self) -> None:
        self.leak_list = []

    def increase_leak_list(self):
        self.leak_list.append("-" * 100000)


def main():
    leakClass = LeakClass()

    while True:
        time.sleep(3)
        print("Increase the memory leak")
        leakClass.increase_leak_list()



if __name__ == '__main__':
    main()
```

When I run this script with 

```bash
fil-profile run test_script.py
```

And I send the signal with 

```bash
kill -s SIGUSR2 <process-pid>
```

The script freeze. The output of the script is:

```bash
$ fil-profile run ./test_script.py 
=fil-profile= Memory usage will be written out at exit, and opened automatically in a browser.
=fil-profile= You can also run the following command while the program is still running to write out peak memory usage up to that point: kill -s SIGUSR2 100661
Increase the memory leak
Increase the memory leak
Increase the memory leak
=fil-profile= Preparing to write to fil-result
```

The files peak-memory.prof and  peak-memory-source.prof are created into the folder fil-result/ but the file peak-memory-source.prof is empty.

**Comment by itamarst** [comment]
That sounds frustrating, and indeed I can reproduce the problem. Guess I need (a) to fix this and (b) a test for SIGUSR2.

**Comment by itamarst** [comment]
Looks like a reentrancy issue, dumping the report allocates memory, which then tries to track allocations, leading to deadlock on the state-tracking mutex.

**Comment by itamarst** [comment]
You tried the wheel from the PR?

**Comment by gaspard-quenard** [comment]
No, I compiled the code from the PR with the Makefile.
