### ISSUE TITLE
Can't install versions after 2011.8.0 on macos 11.6

### ISSUE THREAD

**Issue by avivrosenberg** [pythonspeed/filprofiler#253]
I'm not sure whether this issue is specific to fil, but I haven't encountered it with other packages.

I'm on MacOS 11.6 (Big Sur) with python 3.8.12 installed via `conda`.
After installing and running `filprofiler` via `pip`, I encountered issue #230. But it from the conclusion of that issue it should have been resolved in the latest version. So I checked and saw that I had `2011.8.0`.

I tried specifying the version explicitly, but only versions up to `2021.8.0` are shown:
```shell
% pip install 'filprofiler==2021.11.0'                                                                                                                                        ✹ ✭
ERROR: Could not find a version that satisfies the requirement filprofiler==2021.11.0 (from versions: 0.5.3, 0.6.0, 0.7.0, 0.7.1, 0.7.2, 0.8.0, 0.9.0, 0.10.0, 0.11.0, 0.12.0, 0.13.0, 0.13.1, 0.14.0, 0.14.1, 0.16.0, 0.17.0, 2021.3.0, 2021.4.0, 2021.4.1, 2021.4.2, 2021.4.3, 2021.4.4, 2021.5.0, 2021.7.0, 2021.7.1, 2021.8.0)
ERROR: No matching distribution found for filprofiler==2021.11.0
```

I suspected it was related to my platform version, perhaps there's no matching wheel. But I saw on `PyPI` that there seem to be wheels for `macosx_11_0`. So then I tried manually installing the relevant wheel:
```shell
% pip install https://files.pythonhosted.org/packages/3f/6a/bb68cd1e0220b6d62c8ba91e25799233542fc5fec42bde2c1c3379f5714a/filprofiler-2021.11.0-cp38-cp38-macosx_11_0_x86_64.whl
ERROR: filprofiler-2021.11.0-cp38-cp38-macosx_11_0_x86_64.whl is not a supported wheel on this platform.
```

I also re-tried both of the above commands with a fresh minimal conda env that only contained `python` and `pip`, thinking perhaps a clean install of `python`/`pip` would update the platform version.

Looking at the wheels for `2011.8.0` I see that the platform for those is `macosx_10_15`.
So, I think, that either somehow fil's wheels are not labelled correctly, or perhaps my `pip` is wrong about which platform I have? Apologies if this issue is not fil-specific, but I though it might be because I couldn't find anything online about `pip` being wrong about the platform version.

**Comment by itamarst** [comment]
Hi, yeah, the wheels aren't built for older versions of macOS. My previous attempt at supporting this failed, but I will try again if I have time.

**Comment by itamarst** [comment]
I misunderstood (not a macOS user). the 10.15 wheel should work on macOS 11.... so maybe the issue is you're on a M1 mac?

**Comment by avivrosenberg** [comment]
Thanks for your help. 
Unfortunately no, I have an old intel Mac. The 10.15 wheel works for me, but for version `2021.8.0`. From what I see there's no 10.15 wheel for the newer versions.  But the weird thing is that my macOS is actually 11.6, not 10.15. Even so, pip refuses to upgrade me, claiming there's no newer version for my platform.

**Comment by itamarst** [comment]
What version of `pip` do you have?

**Comment by avivrosenberg** [comment]
I saw the docs about requiring pip newer than 19, I have:

```shell
% pip --version
pip 21.2.4
```

**Comment by itamarst** [comment]
Hm. Well, I'm gonna do another release with 10.15 wheels restored later today, so you can try that.

**Comment by avivrosenberg** [comment]
Thanks! I'll try it and report back.

**Comment by itamarst** [comment]
OK, new release is now available.

**Comment by itamarst** [comment]
... and for some reason macOS wheels weren't uploaded :( So I will have to do another pass at this.

**Comment by itamarst** [comment]
OK, release 2011.11.2 is now available with new macOS wheels. If that doesn't fix your problem please re-open this issue.

**Comment by avivrosenberg** [comment]
Solved, thanks!
