### ISSUE TITLE
ValueError: invalid literal for int() with base 10

### ISSUE THREAD

**Issue by Commaster** [pythonspeed/filprofiler#277]
The last line of _utils.py spits out this error.

```
Traceback (most recent call last):
  File ".../bin/fil-profile", line 8, in <module>
    sys.exit(stage_1())
  File ".../filprofiler/_script.py", line 201, in stage_1
    if glibc_version() >= (2, 30) and exists(LD_LINUX):
  File ".../filprofiler/_utils.py", line 25, in glibc_version
    return tuple(map(int, get_libc_version().split(b".")[:2]))
ValueError: invalid literal for int() with base 10: b'20-2014'
```

Checking the value of `get_libc_version()` manually returns `b'2.20-2014.11'` (This is a NAS)

Should the `.split` include `-` as well?

**Comment by itamarst** [comment]
Oops. Will try to get fix out today.

What're you trying to profile on your NAS, if I can ask?

**Comment by itamarst** [comment]
Release 2021.12.2 should be out in a few minutes.

**Comment by Commaster** [comment]
> Oops. Will try to get fix out today.
> 
> What're you trying to profile on your NAS, if I can ask?

Parsing a large data set that I can't fit on my PC, which sometimes allocates 5 times more memory (with results) than expected. And the network isn't fast enough to access the data remotely.
