### ISSUE TITLE
Wrong command in documentation of the profiling API

### ISSUE THREAD

**Issue by kdebrab** [pythonspeed/filprofiler#291]
Thanks for creating this nice memory profiler!

While trying it out, I noted an error in the documentation:

In https://pythonspeed.com/fil/docs/fil/api.html#2-run-your-script-with-fil, the following:

```console
$ filprofiler python yourscript.py --config=myconfig
```

should actually be:

```console
$ fil-profile python yourscript.py --config=myconfig
```

Also in the subsequent paragraph, `filprofiler` should be replaced by `fil-profile` (twice).

**Comment by itamarst** [comment]
Thanks for the bug report!
