### ISSUE TITLE
Results filename causing file system issues

### ISSUE THREAD

**Issue by cheshrkat** [pythonspeed/filprofiler#336]
The fil results filename format includes colons: `2022-03-15T11:07:13.361` ...which I only really noticed when a backup process freaked out about them.

![fil-filename-issue](https://user-images.githubusercontent.com/307712/159218411-2f182dc5-116c-41f7-8a37-1941261a2d62.png)

Not a massive problem as I can exclude these from backups, but a safer default would be to replace colons (and probably the dots for good measure), leading to something like `2022-03-15T11-07-13_361`

(edit - originally said slashes but this was a sanitised copy, not the original error)

**Comment by itamarst** [comment]
Oh hm never thought about the impact that would have on WSL, since colons are fine on Linux.

**Comment by cheshrkat** [comment]
Thanks for fixing this, and so quickly! :)
