### ISSUE TITLE
No stack counts found

### ISSUE THREAD

**Issue by robertjackson** [pythonspeed/filprofiler#351]
I get the following error:
fil-profile= Error writing SVG: I/O error: No stack counts found
running your sample program on OS X Catalina 10.15.7
Python version 3.9.9
There is no information in the generated report.

**Comment by itamarst** [comment]
Hi,

Sorry it's not working.

Is it possible for you to provide a minimal Python program that demonstrates this when profiled? It'd be good to know if this happens for all problems, or just some problems.

Also, how did you install Python 3?

**Comment by itamarst** [comment]
Unfortunately I can't really debug this; closing for now. If anyone ever see this, please open a new issue!
