### ISSUE TITLE
Couldn't load aligned_alloc(): dlsym(RTLD_NEXT, aligned_alloc): symbol not found

### ISSUE THREAD

**Issue by derrickk23** [pythonspeed/filprofiler#36]
On Mac OS X, Mojave Version 10.14.6, Darwin Kernel Version 18.7.0: Mon Feb 10 21:08:45 PST 2020; root:xnu-4903.278.28~1/RELEASE_X86_64 x86_64

running:

fil-profile run test.py

where test.py just prints hello gives the error:

Couldn't load aligned_alloc(): dlsym(RTLD_NEXT, aligned_alloc): symbol not found

**Comment by itamarst** [comment]
Thank you for the bug report! I will try to fix this in the near future.
