### ISSUE TITLE
Difference in Max Memory from Fil and PSRecord

### ISSUE THREAD

**Issue by afshimono** [pythonspeed/filprofiler#400]
## Version information
Fil: 2022.7.1
Python: 3.9.13 (main, Aug  2 2022, 11:20:39) 
[GCC 10.2.1 20210110]

First of all, thanks for making this tool available as an open-source project. ;D
I have followed the tutorial from [this page](https://pythonspeed.com/articles/python-server-memory-leaks/), but my PSRecord is showing a larger memory consumption (which is similar to what I am seeing in the prod server in Google App Engine) of around 270Mb, but Fil is showing a much lower value of 60Mb.

We are using Flask2, I am using fil to call Flask. I noticed that PSRecord was showing a lower value until I added the `--include-children` param.  Am I missing some command line option to make fil run properly?

I have used fil in the past with Flask 1.x.x and it worked correctly.

Thanks in advance.

**Comment by itamarst** [comment]
At the moment Fil does not support profiling subprocesses, so you'll need to run Flask in a mode where it doesn't start subprocesses.

If you're using `flask run`, the defaults are fine, but using the `--reload` option will cause problems for Fil.

**Comment by afshimono** [comment]
Thanks for your fast reply, @itamarst !
I tried running both using `flask run` and calling the main file with `python main.py`, and both had the same issue with memory.
I just tried calling it with `flask run --no-reload` and making sure debug mode was disabled, but no luck. Let me know if you have more suggestions, really appreciate it.

**Comment by itamarst** [comment]
Also note that Fil doesn't count memory usage from:

1. The Python interpreter.
2. The operating system filesystem cache, where it caches file contents in memory.

However, given the behavior of `psrecord`, it does seem like subprocesses are the issue. Are you running any subprocesses as part of your application?

You can also try https://github.com/bloomberg/memray, which I think supports (Python) subprocesses.

**Comment by afshimono** [comment]
Awesome, thanks for your suggestions and your time!
