### ISSUE TITLE
segfault on macOS

### ISSUE THREAD

**Issue by jackkwok** [pythonspeed/filprofiler#412]
I am new to fil_profiler and it seems like a nice tool that I can use.  

However, I tried to run the sample code on Mac OS but I got a segfault.  

example.py:
```
import numpy as np

def make_big_array():
    return np.zeros((1024, 1024, 50))

def make_two_arrays():
    arr1 = np.zeros((1024, 1024, 10))
    arr2 = np.ones((1024, 1024, 10))
    return arr1, arr2

def main():
    arr1, arr2 = make_two_arrays()
    another_arr = make_big_array()


main()
```

segfault showing in output:
```
% fil-profile run example.py
=fil-profile= Memory usage will be written out at exit, and opened automatically in a browser.
=fil-profile= You can also run the following command while the program is still running to write out peak memory usage up to that point: kill -s SIGUSR2 56717
zsh: segmentation fault  fil-profile run example.py
```

My env:
```
% python -V
Python 3.7.7
% pip freeze | grep filprofi
filprofiler==2022.9.0
```

please help.

**Comment by itamarst** [comment]
Sorry it didn't work. What version of macOS? And is this a Silicon (M1/M2) machine or x86?

**Comment by jackkwok** [comment]
@itamarst :
My machine is running Mac OS Catalina 10.15.7
Intel Core i9 CPU x86.

Let me know if there is anything you want me to try.

**Comment by itamarst** [comment]
Next step: I will try on my M1 mac via https://towardsdatascience.com/how-to-use-manage-multiple-python-versions-on-an-apple-silicon-m1-mac-d69ee6ed0250

If that doesn't reproduce might need to get a VM or something (or maybe GitHub Actions could do?).

**Comment by itamarst** [comment]
Been having trouble getting lldb to cooperate on ARM Mac, so I tried Python 3.9 ARM version of Fil, and that worked.

Next will try Python 3.7 ARM version.

**Comment by itamarst** [comment]
3.7 ARM Python is not available in homebrew. 3.8 works fine.

So I guess I need to either figure out how to get reasonable debugging, or I need an x86 mac :(

**Comment by itamarst** [comment]
@jackkwok could you try with Python 3.8 or later?

**Comment by itamarst** [comment]
On my ARM mac, 3.8 x86_64 did work, unlike 3.7. So maybe it's a 3.7 issue...

**Comment by itamarst** [comment]
Managed to get some info from macOS crash logs, but it's... not helpful. So I'm going to approach this from a different angle: make sure smoke tests get run on the wheels after they're built.

**Comment by itamarst** [comment]
v2022.09.2 should be on PyPI within the hour, let me know if you still have issues.
