### ISSUE TITLE
Ability to run filprofiler as a module

### ISSUE THREAD

**Issue by eyaltrabelsi** [pythonspeed/filprofiler#82]
I would love to be able to run filprofiler as a module in a similar manner to memory_profiler and cprofiler.
`python -m filprofiler example.py`

**Comment by itamarst** [comment]
Should be doable, yeah. What's the motivation for running it that way, if I can ask?

**Comment by eyaltrabelsi** [comment]
@itamarst there are a few reasons:
- The most important one is that most profilers are used this one so switching from 
`python -m memory_profiler foo.py ` to `filprofiler will be easier python -m filprofiler foo.py`
- Another thing if u don't work with virtualenvs its harder to pick which python version to choose ([similar to pip](https://stackoverflow.com/questions/58646030/pip-vs-python-m-pip-why-pip-command-throws-a-module-object-is-not-callable-erro))
- Lastly, the way imports works is a bit different but not sure if it's problematic or not
