### ISSUE TITLE
Be slightly more clear in the documentation about what is being tracked

### ISSUE THREAD

**Issue by dralley** [pythonspeed/filprofiler#90]
This blog post is pretty clear and unambiguous about how Fil works:

> Instead of measuring random snapshots in time, Fil figures out your bottleneck: the moment in time your memory usage is highest. And then it tells you exactly **where that memory was allocated**: which callstacks were responsible, down to the level of individual lines of Python code.

https://pythonspeed.com/products/filmemoryprofiler/

The README is slightly less clear about this, it's easier to get the impression that it's tracking where the memory currently resides rather than where it was allocated.  

> Your code reads some data, processes it, and uses too much memory. In order to reduce memory usage, **you need to learn what code is responsible, and specifically what code is responsible for peak memory usage**.

It's an important distinction because there are other tools such as pympler/muppy which do attempt to figure out which objects are holding onto the memory (rather than where the was originally allocated).

(Note that this isn't a value judgement against either tool since both strategies are very useful, but they can be useful in different circumstances.  If you're creating large objects and then dumping them onto a queue, and not processing them quickly enough or handling backpressure, using the FIL approach, the hotspot will be the function creating all of the objects whereas the memory buildup is actually occurring inside the queue.  But conversely there's other situations where the FIL approach is more useful.)

Thank you for this tool, I've found it really helpful.

**Comment by itamarst** [comment]
Thanks, that's a good idea; might also write a blog post comparing those two with memory-profiler, a third perspective on memory (and again, useful in some contexts but not others).

What're you using Fil for, if I can ask?

**Comment by dralley** [comment]
Excellent description!  Thanks.

To answer your question, we were attempting to use it to track down a memory leak - that eventually ended up being in a C extension that we were using.  We still weren't sure what was causing it when I filed this though.

**Comment by itamarst** [comment]
Thank you, an hope it was useful!
