### ISSUE TITLE
Getting a core dump when I run fil

### ISSUE THREAD

**Issue by winash12** [pythonspeed/filprofiler#99]
```
thread '<unnamed>' panicked at 'cannot access a Thread Local Storage value during or after destruction: AccessError', /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/thread/local.rs:248:26
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:483
   1: core::panicking::panic_fmt
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/panicking.rs:85
   2: core::option::expect_none_failed
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/option.rs:1234
   3: pymemprofile_api::memorytracking::add_allocation
   4: add_allocation
             at /src/filprofiler/_filpreload.c:286
   5: calloc
             at /src/filprofiler/_filpreload.c:316
   6: g_malloc0
   7: <unknown>
   8: g_slice_free1
   9: __nptl_deallocate_tsd.part.0
  10: start_thread
  11: clone
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
fatal runtime error: failed to initiate panic, error 5
```

Getting this error when I run my script . How can I fix this ? 

Python 3.8, Ubuntu 20.04 and Latest version of fil

**Comment by itamarst** [comment]
Sorry it didn't work.

1. Can you share the code you ran?
2. Does the same issue with happen if you install v0.10? E.g. `pip install --upgrade filprofiler==0.10` if using `pip`, or `conda install -c conda-forge filprofiler=0.10` on Conda.

**Comment by winash12** [comment]
@itamarst I get the same issue when I run the 0.10 version as well. I can share the code by emailing it to you if that is OK with you.

**Comment by itamarst** [comment]
That'd be great, thank you! itamar@pythonspeed.com

**Comment by itamarst** [comment]
Looking through the stack trace:

1. The thread is shutting down (which is when `__nptl_deallocate_tsd` happens, cleaning up thread-local storage).
2. Some code allocates some memory; perhaps some sort of thread-shutdown callback.
3. This reaches Fil's tracking code.
4. Fil tries to use thread-local storage.
5. BOOM.

I should be able to create a reproducer where I `pthread_cleanup_push` (https://man7.org/linux/man-pages/man3/pthread_cleanup_push.3.html) a function that does a `malloc()`.

**Comment by itamarst** [comment]
Thread cleanup handler wasn't able to reproduce the issue, but a thread-local storage destructor was able to. So now I have a reproducer, next to fix the bug.
